import komal from './komal.png'
import template from './template.jpg'

export const DentistsData = [
    {img: template, 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: komal , 
    name: "Dr. Komal Jain, DMD",
    about: "Dr. Komal Jain is a General Dentist at Komal Jain Dentistry in Mississauga with a dental experience of more than 15 Years. She is one of the best dentist in Toronto. She graduated in Dentistry from Boston University, US and then went on to receive her Licensing from University of Toronto Faculty of Dentistry after completing the National Dental Examining Board of Canada.",
    location: "73 Dundas St W, Mississauga, ON L5B 1H7 ",
    number: "(905) 232-6588",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    }
]