import tci from './tci.png'
import template from './template.jpg'

export const ImmigrationData = [
    {img: template, 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: tci , 
    name: "Town Centre Immigration",
    about: "We're a licensed Canadian immigration consultant and is authorized by the Canadian government to represent your interests in all immigration matters. we develop effective immigration strategy for each client individually. Each case is unique and careful evaluation of your particular matter by a qualified immigration consultant is essential.",
    location: "73A Dundas St W,Mississauga,ON L5B 1H7 ",
    number: "(+1) 6472912373",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    }
]