import vinod from './vinod.png'
import template from './template.jpg'

export const RealtorData = [
    {img: template, 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: vinod , 
    name: "Vinod Maun, Realtor",
    about: "Welcome to our real estate business! Our team of experienced realtors is committed to providing exceptional service to help you achieve your real estate goals. With our local market expertise, personalized guidance, and professionalism, we aim to exceed your expectations.",
    location: "503-55 City Centre Dr., Mississauga, Ontario, L5B 1M3",
    number: "647-291-2373",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    },
    {img: template , 
    name: "Madelyn Cline",
    about: "Madelyn Renee Cline (born December 21, 1997) is an American actress and model. She is known for her roles as Sarah Cameron on the Netflix teen drama series Outer Banks (2020–present) and as Whiskey in Rian Johnson's mystery film Glass Onion: A Knives Out Mystery (2022).",
    location: "torronto,canada",
    number: "9872629802",
    }
]